[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.40.0",
    "pandas>=2.2.3",
    "plotly>=6.1.1",
    "pypdf2>=3.0.1",
    "requests>=2.32.3",
    "streamlit>=1.45.1",
]
